### ISSUE TITLE
Lack in responsiveness of the app specially in mobile devices and issue in design.

### ISSUE THREAD

**Issue by Abhijeet-Nema** [codewizard26/weather-wizard-app#16]
### Hey @codewizard26, the issue in the design part of your app needs to be addressed for the effective and convenient use of your app.

**First, the major issue is the unresponsive behavior of the app making it a bad experience for mobile users.**

![Weather-wizard - Brave 11-Oct-22 12_39_44 AM (2)](https://user-images.githubusercontent.com/85112134/194936863-b28420a3-3d3b-4565-899d-f6c3825221d3.png)

_After fixing this issue, it will responsively behave_

![Weather-wizard - Brave 11-Oct-22 12_42_52 AM (2)](https://user-images.githubusercontent.com/85112134/194937009-4bb98241-199c-46d5-9567-fa99b92b8f84.png)

**There were still some inconsistencies regarding the design aspect of the app which can be easily fixed**

![Weather-wizard - Brave 11-Oct-22 12_15_17 AM](https://user-images.githubusercontent.com/85112134/194935853-10644528-84bf-4ae6-bc24-70cd1d3a79fa.png)

After some fixes, the glance at the app:
__
![Weather-wizard - Brave 11-Oct-22 12_15_34 AM](https://user-images.githubusercontent.com/85112134/194936125-a2faa606-c641-4e16-beb2-530d18170818.png)

Thanks!

**Comment by codewizard26** [comment]
You can start working on the mentioned changes and if you already have done, you can raise a pr for the same
thank you
