### ISSUE TITLE
Request to fetch weather details sent event when the searched input is empty

### ISSUE THREAD

**Issue by darshanshah1996** [codewizard26/weather-wizard-app#20]
Hi @codewizard26 

Currently, when the user tries to click on the search button when the `search input` is empty we still send a request to fetch weather details.

Thinking of adding validation to show `Search input is empty` similar to the way we show `No results found when user enters invalid location`

Can you assign the issue to me

![image](https://user-images.githubusercontent.com/26178486/195077048-2ddbc46e-87e2-48de-9c56-8ed846cab5d8.png)

**Comment by codewizard26** [comment]
sure you can work upon it, assigning the task to you

**Comment by darshanshah1996** [comment]
Closing the issue as the related pr https://github.com/codewizard26/weather-wizard-app/pull/21 is merged
