### ISSUE TITLE
Add the feature of fetching the current location

### ISSUE THREAD

**Issue by prajwalprogrammer** [codewizard26/weather-wizard-app#28]
Can I try to add the feature of fetching the current location of user and as app loads whether will set according to fetched location.

**Comment by codewizard26** [comment]
sure

**Comment by prajwalprogrammer** [comment]
please assign me.

**Comment by prajwalprogrammer** [comment]
kindly check my PR: https://github.com/codewizard26/weather-wizard-app/pull/29
