### ISSUE TITLE
Dark/Light theme Icon not aligned

### ISSUE THREAD

**Issue by Luedch93** [codewizard26/weather-wizard-app#34]

**Comment by codewizard26** [comment]
which icon ?

**Comment by Luedch93** [comment]
I can work on this issue, fixing the alignment of the dark theme icon
![image](https://user-images.githubusercontent.com/14883509/196229483-6841dbf3-fbfc-4f59-b1a0-99a13cd3a93b.png)

**Comment by codewizard26** [comment]
sure, go ahead
