### ISSUE TITLE
Feature to show current date and time on the app.

### ISSUE THREAD

**Issue by Rickey07** [codewizard26/weather-wizard-app#9]
Hi ,

it would be great if we will create an feature to display the current time and date.

I am ready to do that if you'll assign me the task

**Comment by codewizard26** [comment]
Sure .. you can work on it

**Comment by Rickey07** [comment]
Hi Which one is actual design as the deployed site is different from the code on repo

**Comment by Rickey07** [comment]
![Screenshot 2022-10-10 140623](https://user-images.githubusercontent.com/59111961/194827223-f8f970e0-abcf-41aa-9da6-e6b4e9569734.png)

Hi I've created an pull request for this feature. 

Check attached screenshot!

**Comment by codewizard26** [comment]
the community_uploads branch contains the project which is actually hosted and master branch contains the current project which is being worked upon
you have to work only on master branch as mentioned in readme.md file

**Comment by Rickey07** [comment]
Hi ,

Done with current time and Date Feature. Please check the PR.

**Comment by Rickey07** [comment]
It's Done Now
